"use strict";

const images = [
  {
    title: "Autumn sunrise",
    fullRes: "paintings/Autumn-sunrise.jpg",
    lowRes: "paintings/low-res/Autumn-sunrise.jpg",
    height: 1858,
    id: 0,
  },
  {
    title: "Bern",
    fullRes: "paintings/Bern.jpg",
    lowRes: "paintings/low-res/Bern.jpg",
    height: 1255,
    id: 1,
  },
  {
    title: "Bologna",
    fullRes: "paintings/Bologna.jpg",
    lowRes: "paintings/low-res/Bologna.jpg",
    height: 1651,
    id: 2,
  },
  {
    title: "Breslau",
    fullRes: "paintings/Breslau.jpg",
    lowRes: "paintings/low-res/Breslau.jpg",
    height: 2020,
    id: 3,
  },
  {
    title: "Center of the earth",
    fullRes: "paintings/Center-of-the-earth.jpg",
    lowRes: "paintings/low-res/Center-of-the-earth.jpg",
    height: 2500,
    id: 4,
  },
  {
    title: "Cinque terre",
    fullRes: "paintings/Cinque-terre.jpg",
    lowRes: "paintings/low-res/Cinque-terre.jpg",
    height: 3753,
    id: 5,
  },
  {
    title: "Copper",
    fullRes: "paintings/Copper.jpg",
    lowRes: "paintings/low-res/Copper.jpg",
    height: 1955,
    id: 6,
  },
  {
    title: "Early spring",
    fullRes: "paintings/Early-spring.jpg",
    lowRes: "paintings/low-res/Early-spring.jpg",
    height: 2041,
    id: 8,
  },
  {
    title: "Enough is enough",
    fullRes: "paintings/Enough-is-enough.jpg",
    lowRes: "paintings/low-res/Enough-is-enough.jpg",
    height: 2072,
    id: 9,
  },
  {
    title: "Forest",
    fullRes: "paintings/Forest.jpg",
    lowRes: "paintings/low-res/Forest.jpg",
    height: 1437,
    id: 10,
  },
  {
    title: "Golden landscape",
    fullRes: "paintings/Golden-landscape.jpg",
    lowRes: "paintings/low-res/Golden-landscape.jpg",
    height: 1270,
    id: 11,
  },
  {
    title: "Good as hell",
    fullRes: "paintings/Good-as-hell.jpg",
    lowRes: "paintings/low-res/Good-as-hell.jpg",
    height: 873,
    id: 12,
  },
  {
    title: "Grue and bleen",
    fullRes: "paintings/Grue-and-bleen.jpg",
    lowRes: "paintings/low-res/Grue-and-bleen.jpg",
    height: 817,
    id: 13,
  },
  {
    title: "Honey field",
    fullRes: "paintings/Honey-field.jpg",
    lowRes: "paintings/low-res/Honey-field.jpg",
    height: 1720,
    id: 14,
  },
  {
    title: "Infra black",
    fullRes: "paintings/Infra-black.jpg",
    lowRes: "paintings/low-res/Infra-black.jpg",
    height: 1256,
    id: 15,
  },
  {
    title: "Infra white",
    fullRes: "paintings/Infra-white.jpg",
    lowRes: "paintings/low-res/Infra-white.jpg",
    height: 848,
    id: 16,
  },
  {
    title: "Living coral",
    fullRes: "paintings/Living-coral.jpg",
    lowRes: "paintings/low-res/Living-coral.jpg",
    height: 844,
    id: 17,
  },
  {
    title: "Lonely island",
    fullRes: "paintings/Lonely-island.jpg",
    lowRes: "paintings/low-res/Lonely-island.jpg",
    height: 1999,
    id: 18,
  },
  {
    title: "Look up for answers",
    fullRes: "paintings/Look-up-for-answers.jpg",
    lowRes: "paintings/low-res/Look-up-for-answers.jpg",
    height: 1419,
    id: 19,
  },
  {
    title: "Melting landscape",
    fullRes: "paintings/Melting-landscape.jpg",
    lowRes: "paintings/low-res/Melting-landscape.jpg",
    height: 2051,
    id: 21,
  },
  {
    title: "Murmuration",
    fullRes: "paintings/Murmuration.jpg",
    lowRes: "paintings/low-res/Murmuration.jpg",
    height: 785,
    id: 22,
  },
  {
    title: "Out of the blue",
    fullRes: "paintings/Out-of-the-blue.jpg",
    lowRes: "paintings/low-res/Out-of-the-blue.jpg",
    height: 2059,
    id: 23,
  },
  {
    title: "Pearly sky",
    fullRes: "paintings/Pearly-sky.jpg",
    lowRes: "paintings/low-res/Pearly-sky.jpg",
    height: 2500,
    id: 24,
  },
  {
    title: "Pink sky",
    fullRes: "paintings/Pink-sky.jpg",
    lowRes: "paintings/low-res/Pink-sky.jpg",
    height: 1256,
    id: 25,
  },
  {
    title: "Poppies field",
    fullRes: "paintings/Poppies-field.jpg",
    lowRes: "paintings/low-res/Poppies-field.jpg",
    height: 836,
    id: 26,
  },
  {
    title: "Second skin",
    fullRes: "paintings/Second-skin.jpg",
    lowRes: "paintings/low-res/Second-skin.jpg",
    height: 2838,
    id: 27,
  },
  {
    title: "Space",
    fullRes: "paintings/Space.jpg",
    lowRes: "paintings/low-res/Space.jpg",
    height: 2095,
    id: 28,
  },
  {
    title: "Sparkling lake",
    fullRes: "paintings/Sparkling-lake.jpg",
    lowRes: "paintings/low-res/Sparkling-lake.jpg",
    height: 1037,
    id: 29,
  },
  {
    title: "Spectrum of thoughts",
    fullRes: "paintings/Spectrum-of-thoughts.jpg",
    lowRes: "paintings/low-res/Spectrum-of-thoughts.jpg",
    height: 2500,
    id: 30,
  },
  {
    title: "Sub dominant",
    fullRes: "paintings/Sub-dominant.jpg",
    lowRes: "paintings/low-res/Sub-dominant.jpg",
    height: 1604,
    id: 31,
  },
  {
    title: "Vespera and prima",
    fullRes: "paintings/Vespera-and-prima.jpg",
    lowRes: "paintings/low-res/Vespera-and-prima.jpg",
    height: 867,
    id: 32,
  },
  {
    title: "Vilnus",
    fullRes: "paintings/Vilnus.jpg",
    lowRes: "paintings/low-res/Vilnus.jpg",
    height: 1616,
    id: 33,
  },
  {
    title: "Water landscape",
    fullRes: "paintings/Water-landscape.jpg",
    lowRes: "paintings/low-res/Water-landscape.jpg",
    height: 852,
    id: 34,
  },
  {
    title: "Water lilies",
    fullRes: "paintings/Water-lilies.jpg",
    lowRes: "paintings/low-res/Water-lilies.jpg",
    height: 1933,
    id: 35,
  },
  {
    title: "Widawa river",
    fullRes: "paintings/Widawa-river.jpg",
    lowRes: "paintings/low-res/Widawa-river.jpg",
    height: 2022,
    id: 36,
  },
  {
    title: "World united",
    fullRes: "paintings/World-united.jpg",
    lowRes: "paintings/low-res/World-united.jpg",
    height: 2500,
    id: 37,
  },
];

// Use python's os.listdir(path) to make a list of files

const paintings = [
  "Autumn-sunrise.jpg",
  "Bern.jpg",
  "Bologna.jpg",
  "Breslau.jpg",
  "Center-of-the-earth.jpg",
  "Cinque-terre.jpg",
  "Copper.jpg",
  "Early-spring.jpg",
  "Enough-is-enough.jpg",
  "Forest.jpg",
  "Golden-landscape.jpg",
  "Good-as-hell.jpg",
  "Grue-and-bleen.jpg",
  "Honey-field.jpg",
  "Infra-black.jpg",
  "Infra-white.jpg",
  "Living-coral.jpg",
  "Lonely-island.jpg",
  "Look-up-for-answers.jpg",
  "Melting-landscape.jpg",
  "Murmuration.jpg",
  "Out-of-the-blue.jpg",
  "Pearly-sky.jpg",
  "Pink-sky.jpg",
  "Poppies-field.jpg",
  "Second-skin.jpg",
  "Space.jpg",
  "Sparkling-lake.jpg",
  "Spectrum-of-thoughts.jpg",
  "Sub-dominant.jpg",
  "Vespera-and-prima.jpg",
  "Vilnus.jpg",
  "Water-lilies.jpg",
  "Water-landscape.jpg",
  "Widawa-river.jpg",
  "World-united.jpg",
];

// let imgIndex = 0;

// for (let i = 0; i < paintings.length - 1; i++) {
//   let item = {
//     id: i,
//     title: `${paintings[imgIndex]}`.replaceAll("-", " ").replace(".jpg", ""),
//     lowRes: `paintings/low-res/${paintings[imgIndex]}`,
//     fullRes: `paintings/${paintings[imgIndex]}`,
//   };
//   images.push(item);
//   imgIndex++;
//   if (imgIndex > paintings.length - 1) {
//     imgIndex = 0;
//   }
// }

// console.log(images);
